select
    cast(game_id as varchar) as game_id,
    cast(white as varchar) as white_player,
    cast(black as varchar) as black_player,
    cast(white_elo as integer) as white_elo,
    cast(black_elo as integer) as black_elo,
    cast(result as varchar) as result,
    cast(termination as varchar) as termination,
    cast(result_reason as varchar) as result_reason,
    cast(eco_code as varchar) as eco_code,
    cast(opening_family as varchar) as opening_family,
    cast(opening_variation as varchar) as opening_variation,
    cast(time_control_type as varchar) as time_control_type,
    cast(base_time_seconds as integer) as base_time_seconds,
    cast(increment_seconds as integer) as increment_seconds,
    cast(game_date as date) as game_date,
    cast(game_length as integer) as game_length,
    cast(has_clock_data as boolean) as has_clock_data,
    clock_seconds,
    cast(has_capture as boolean) as has_capture,
    cast(capture_count as integer) as capture_count,
    cast(white_castled as boolean) as white_castled,
    cast(black_castled as boolean) as black_castled,
    cast(legal_prefix_length as integer) as legal_prefix_length,
    cast(has_bot_player as boolean) as has_bot_player,
    moves_uci,
    cast(batch_id as varchar) as batch_id,
    extract(year from cast(game_date as date))::integer as year,
    extract(month from cast(game_date as date))::integer as month
from {{ source('lake', 'silver_games') }}
where game_id is not null
